# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083dd86d24a83127d7f1f0412094c6af06efb63771dfddf2d17cfe26d47b33927f037a02c9357c0f72449a18ce67f3c676f69a4592d20001339e04a915a117a1

test:
  secret_key_base: 67a25900508ed57209f2ea196dbc661d085d757dbe2237598557266c1f8eafe9c31e66ab1a9c9f5cf4397addfd77f82e25f5fde23ef83d78b51b64cda17726d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
